/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "tutorialSidebar": [
    {
      "type": "autogenerated",
      "dirName": "."
    }
  ],
  "modules": [
    {
      "type": "category",
      "label": "Module 1: The Robotic Nervous System (ROS 2)",
      "items": [
        "modules/ros2-nervous-system/index",
        {
          "type": "category",
          "label": "ROS 2 Basics & Middleware",
          "items": [
            "modules/ros2-nervous-system/basics/index",
            "modules/ros2-nervous-system/basics/nodes-topics-services",
            "modules/ros2-nervous-system/basics/communication-patterns",
            "modules/ros2-nervous-system/basics/exercises"
          ]
        },
        {
          "type": "category",
          "label": "Python Agents & ROS Integration",
          "items": [
            "modules/ros2-nervous-system/python-integration/index",
            "modules/ros2-nervous-system/python-integration/rclpy-basics",
            "modules/ros2-nervous-system/python-integration/agent-communication",
            "modules/ros2-nervous-system/python-integration/exercises"
          ]
        },
        {
          "type": "category",
          "label": "Humanoid Robot Modeling with URDF",
          "items": [
            "modules/ros2-nervous-system/humanoid-modeling/index",
            "modules/ros2-nervous-system/humanoid-modeling/urdf-structure",
            "modules/ros2-nervous-system/humanoid-modeling/simulation-setup",
            "modules/ros2-nervous-system/humanoid-modeling/exercises"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Module 2: The Digital Twin (Gazebo & Unity)",
      "items": [
        "module2-digital-twin/intro",
        "module2-digital-twin/gazebo-physics",
        "module2-digital-twin/unity-rendering",
        "module2-digital-twin/sensor-simulation",
        "module2-digital-twin/gazebo-setup",
        "module2-digital-twin/urdf-sdf"
      ]
    },
    {
      "type": "category",
      "label": "Module 3: The AI-Robot Brain (NVIDIA Isaac™)",
      "items": [
        "module3-isaac/intro",
        "module3-isaac/isaac-sim",
        "module3-isaac/synthetic-data",
        "module3-isaac/isaac-ros-vslam",
        "module3-isaac/nav2-planning",
        "module3-isaac/perception-manipulation",
        "module3-isaac/reinforcement-learning",
        "module3-isaac/sim-to-real"
      ]
    },
    {
      "type": "category",
      "label": "Module 4: Vision-Language-Action (VLA)",
      "items": [
        "module4-vla/intro",
        "module4-vla/voice-to-action",
        "module4-vla/cognitive-planning",
        "module4-vla/speech-recognition",
        "module4-vla/multimodal-interaction",
        "module4-vla/capstone-project"
      ]
    }
  ]
};

module.exports = sidebars;